instaImg_crawl/instaPrj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

instaImg_crawl/main/urls.py
# main/urls.py


from . import views

from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import SignUpView, get_photos,get_image_url,proxy_instagram_image

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'), # 추가된 부분
    path('adminwindow/', views.adminwindow, name='adminwindow'),  # admin 패턴 추가
    path('index/', views.index, name='index'),
    path('detail_img/', views.detail_img, name='detail_img'),
    path('folder_list/', views.folder_list, name='folder_list'),  # 이름을 'folder_list'로 지정
    #path('show_folder_images/<str:folder_name>/', views.show_folder_images, name='show_folder_images'),
    path('client/', views.client, name='client'),
    path('folder_list/<str:folder_name>/', views.show_folder_images, name='show_folder_images'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('find_id/', views.find_id, name='find_id'),
    path('find_user/', views.find_user, name='find_user'),
    path('find_pw/', views.find_pw, name='find_pw'),
    path('find_password/', views.find_password, name='find_password'),
    path('get_photos/', get_photos, name='get_photos'),
    path('api/get-photos/', get_photos, name='get_photos'),
    path('api/get-image-url/', get_image_url, name='get_image_url'),
    path('api/proxy-instagram-image/<path:image_url>/', proxy_instagram_image, name='proxy_instagram_image'),

]

instaImg_crawl/main/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    user_folder = models.CharField(max_length=255, blank=True, null=True)

class YourImageModel(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    search_term = models.CharField(max_length=255)
    image_url = models.URLField()
    additional_info = models.TextField()

    def __str__(self):
        return f"{self.search_term} - {self.image_url}"

    class Meta:
        db_table = 'img'  # 여기에 특정한 테이블 이름을 지정할 수 있습니다.


class Photo1(models.Model):
    id = models.BigAutoField(primary_key=True)
    keyword = models.CharField(max_length=255)
    image_src = models.TextField(null=True)

class UserImage(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    keyword = models.CharField(max_length=255)
    image_url = models.URLField()
    additional_info = models.TextField()

    def __str__(self):
        return f"{self.keyword} - {self.image_url}"

    class Meta:
        db_table = 'user_image'

instaImg_crawl/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '아이디'}))
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': '성'}))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': '이름'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': '이메일 주소'}))  # Add this line

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("비밀번호가 일치하지 않습니다.")
        if len(password2) < 8:
            raise ValidationError('비밀번호는 최소 8자 이상이어야 합니다.')
        return password2

instaImg_crawl/main/views.py
import base64

from django.shortcuts import render
from django.http import JsonResponse
from urllib.request import urlopen
from urllib.parse import quote_plus
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from django.shortcuts import render, redirect
import time
import os
from django.http import Http404
from base64 import b64encode
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Photo1, CustomUser
from django.http import HttpResponse
import requests  # requests 모듈을 임포트
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('main:login')
    template_name = 'registration/signup.html'

def index(request):
    return render(request, 'main/index.html')

def main(request):
    return render(request, 'registration/main.html')

def client(request):

    return render(request, 'main/client.html')

def proxy_instagram_image(request, image_url):
    try:
        # Instagram 이미지에 대한 요청을 수행
        response = requests.get(image_url)

        # 응답을 그대로 클라이언트에게 전달
        return HttpResponse(response.content, content_type=response.headers['Content-Type'])
    except Exception as e:
        return HttpResponse(str(e), status=500)
def find_id(request):
    return render(request, 'main/find_id.html')

def find_pw(request):
    return render(request, 'main/find_pw.html')

def adminwindow(request):
    # admin 페이지의 내용을 처리하는 코드 추가
    return render(request, 'main/adminwindow.html')  # 예시로 'main/admin.html'로 렌더링하도록 설정

def find_user(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')

        try:
            # 변경된 컬럼명에 맞게 수정
            user = CustomUser.objects.get(first_name=first_name, last_name=last_name, email=email)
            return JsonResponse({'found': True, 'username': user.username})
        except CustomUser.DoesNotExist:
            return JsonResponse({'found': False})

    return render(request, 'find_id.html')

def find_password(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')

        try:
            # 변경된 컬럼명에 맞게 수정
            user = CustomUser.objects.get(username=username, first_name=first_name, last_name=last_name, email=email)
            return JsonResponse({'found': True, 'password': user.password})
        except CustomUser.DoesNotExist:
            return JsonResponse({'found': False})

    return render(request, 'find_pw.html')

@csrf_exempt
def get_image_url(request):
    if request.method == 'POST':
        keyword = request.POST.get('keyword', '')
        photo = Photo1.objects.filter(keyword=keyword).first()

        if photo:
            return JsonResponse({'image_url': photo.image_src})
        else:
            return JsonResponse({'error': 'Image not found for the given keyword'}, status=404)
def get_photos(request):
    photos = Photo1.objects.all().values('keyword', 'image_src')
    return JsonResponse(list(photos), safe=False)
def detail_img(request):
    baseUrl = 'https://www.instagram.com/explore/tags/'
    plusUrl = request.GET.get('account')
    plusUrl = str(plusUrl)
    url = baseUrl + quote_plus(plusUrl)

    save_folder = os.path.join(r'C:/Users/user/PycharmProjects/instaImg_crawl/instaImg_crawl/img/', plusUrl)
    os.makedirs(save_folder, exist_ok=True)

    # 크롬 드라이버 설정
    chrome_options = Options()
    chrome_options.add_argument('--headless')  # 화면 최소화 옵션 추가
    driver = webdriver.Chrome(
        executable_path=r'C:\Users\user\PycharmProjects\instaImg_crawl\instaImg_crawl\chromedriver.exe',
        options=chrome_options
    )

    driver.get(url)

    pageDown = 10
    while pageDown:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(1)
        pageDown -= 1

    html = driver.page_source
    soup = BeautifulSoup(html, features="html.parser")

    instaImg = soup.select('div.grid-item>div>a')
    instaText = soup.select('div.grid-item>div.p-4>div.break-words')

    imgSrcList = []
    textList = []
    posts = {}

    for i in instaImg:
        imgSrcList.append(i.img['src'])

    for i in instaText:
        textList.append(i)

    for i in range(len(imgSrcList)):
        img = imgSrcList[i]
        text = textList[i]
        posts.update({img: text})

    insta = soup.select('._aabd._aa8k._al3l')

    n = 1
    for i in insta:
        imgUrl = i.select_one('._aagv').img['src']
        img_path = os.path.join(save_folder, f'{plusUrl}{n}.jpg')

        with urlopen(imgUrl) as f:
            with open(img_path, 'wb') as h:
                img = f.read()
                h.write(img)
            n += 1

    driver.close()

    # 폴더 내의 이미지 목록 가져오기
    folderImagePaths = [os.path.join(save_folder, f'{plusUrl}{i}.jpg') for i in range(1, n)]

    # 이미지를 Base64로 변환하여 리스트에 추가
    base64_images = []
    for img_path in folderImagePaths:
        with open(img_path, 'rb') as image_file:
            base64_image = base64.b64encode(image_file.read()).decode('utf-8')
            base64_images.append(base64_image)

    # JSON 응답으로 이미지 목록 전송
    return JsonResponse({'image_list': base64_images})


def folder_list(request):
    folder_path = r'C:/Users/user/PycharmProjects/instaImg_crawl/instaImg_crawl/img/'
    folder_names = [f for f in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, f))]
    return render(request, 'main/folder_list.html', {'folder_names': folder_names})


def show_folder_images(request, folder_name):
    folder_path = f'C:/Users/user/PycharmProjects/instaImg_crawl/instaImg_crawl/img/{folder_name}/'
    if not os.path.exists(folder_path):
        raise Http404("Folder does not exist")
    image_list = []
    for filename in os.listdir(folder_path):
        if filename.endswith(".jpg") or filename.endswith(".png"):
            with open(f'{folder_path}/{filename}', "rb") as image_file:
                encoded_string = b64encode(image_file.read()).decode('utf-8')
                image_list.append(encoded_string)
    return render(request, 'main/show_folder_images.html', {'folder_name': folder_name, 'image_list': image_list})

instaImg_crawl/main/templates/main/adminwindow.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Admin Login Panel</title>
  <style>
    *{
      padding: 0;
      margin: 0;
      box-sizing: border-box;
      font-family: poppins;
    }

    body{
      background-color: #E8EDF2;
    }

    div.container{
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%,-50%);

      display: flex;
      flex-direction: row;
      align-items: center;

      background-color: white;
      padding: 30px;
      box-shadow: 0 50px 50px -50px darkslategray;
    }

    div.container div.myform{
      width: 270px;
      margin-right: 30px;
    }

    div.container div.myform h2{
      color: #1c1c1e;
      margin-bottom: 20px;
    }

    div.container div.myform input{
      border: none;
      outline: none;
      border-radius: 0;
      width: 100%;
      border-bottom: 2px solid #1c1c1e;
      margin-bottom: 25px;
      padding: 7px 0;
      font-size: 14px;
    }
    div.container div.myform button{
      color: white;
      background-color: #1c1c1e;
      border: none;
      outline: none;
      border-radius: 2px;
      font-size: 14px;
      padding: 5px 12px;
      font-weight: 500;
    }
    div.container div.image img{
      width: 300px;
    }
  </style>
</head>
<body>

  <div class="container">
    <div class="myform">
      <form id="adminForm">
        <h2>ADMIN LOGIN</h2>
        <input type="text" placeholder="Admin Name" disabled> <!-- Admin Name input disabled as it's not used in your current functionality -->
        <input type="password" id="password" placeholder="Password" required>
        <button type="button" onclick="checkAdminPassword()">LOGIN</button>
      </form>
    </div>
    <div class="image">
      <img src="/static/photo/admin.jpg">
    </div>
  </div>

  <script>
        function checkAdminPassword() {
            const actualPassword = "ehrbs123123.";  // Replace with your actual password
            const enteredPassword = document.getElementById("password").value;

            if (enteredPassword === actualPassword) {
                window.location.href = "{% url 'main:index' %}";
            } else {
                alert("Incorrect password. Please try again.");
            }
        }
    </script>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-e54L2BqNqNMS9zjVQwF9OcOQCG9T9RGlC27qAJ6cCSdyZxl1bUqJ9f3drZL5uM5J"
            crossorigin="anonymous"></script>

</body>
</html>

instaImg_crawl/main/templates/main/base.html
<!-- main/templates/main/base.html -->

{% load static %}

<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-content-type-options" content="nosniff">
    <link rel="stylesheet" href="{% static 'main/reset.css' %}">
    <link rel="stylesheet" href="{% static 'main/base.css' %}">
    <link rel="stylesheet" href="{% static 'main/detail_img.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    <title>인스타그램 사진 가져오기</title>

    <style>
        #loading {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: rgba(247, 247, 247, 1);
            padding: 20px;
            border-radius: 5px;
            z-index: 1000;
        }

    #imageGallery {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around;
        box-sizing: border-box;
        padding: 10px; /* 이미지 간격을 조절하기 위한 패딩 추가 */
    }

    #imageGallery img {
        width: calc(33.33% - 20px); /* 이미지 크기를 33.33%로 수정 (좌우 간격은 10px로 가정) */
        margin-bottom: 20px; /* 아래 여백을 추가하여 이미지 간의 수직 간격 설정 */
        box-sizing: border-box;
        border: 2px solid #fff; /* 이미지 사이에 흰색 테두리 추가 */
        object-fit: cover; /* 이미지를 비율 유지하면서 적절히 자르기 */
        max-height: 100%; /* 이미지 최대 높이를 부모 요소에 맞게 설정 */
    }


      .folder-list {
        display: flex;
        flex-wrap: wrap;
        gap: 20px; /* 아이콘 간격 조절 */
        list-style-type: none;
        padding: 0;

      }

      .folder-item {
        width: calc(20% - 20px); /* 가로에 5개씩 정리, 간격은 20px로 가정 */
        box-sizing: border-box;
        margin-bottom: 10px; /* 각 행의 마지막 아이템 아래 간격 조절 */
        float : left;

      }

      .folder-link {
        color: black;
        text-decoration: none;
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
        width: 100%;
      }

      .folder-icon {
        width: 60px; /* 폴더 로고 크기 조절 */
        height: 60px;
        margin-bottom: 5px; /* 아이콘과 텍스트 간격 조절 */
      }

      .folder-name {
        font-size : 18px; /* 폴더명 폰트 크기 조절 */
        text-align : center;
      }


    </style>
</head>

<body>

<div class="wrap" style="background-color: #f7f7f7 !important; height: 80px;">
    <section class="search_section">

            <a href="{% url 'main:index' %}">
                <img style="width: 130px; top: 10px; position: absolute; left: 20px;" src="https://www.instagram.com/static/images/web/mobile_nav_type_logo-2x.png/1b47f9d0e595.png" alt="Instagram Logo">
            </a>

            <form class="search_form" id="searchForm" data-url="{% url 'main:detail_img' %}" method="get">
                <input type="text" style="width: 550px; height: 40px; top: 10px;" placeholder="키워드를 입력하세요.." name="account" id="accountInput">
                    <button type="submit" style="position: absolute; top: 10px; right: 270px; background-color: #b0bcc9; font-size: 20px; text-align: center;">검색</button>
                    <button type="button" onclick="location.href='{% url 'main:folder_list' %}'" style="position: absolute; top: 10px; right: 210px; background-color: #b0bcc9; font-size: 20px; text-align: center;">폴더</button>
                <div style="position: absolute; top: 20px; right: 100px;">
                    <a href="/login" style="color: black;">로그아웃</a>
                </div>
            </form>

    </section>

    <section class="result_section">
        <div id="loading">Loading...</div>
        <div id="imageGallery"></div>
    </section>
</div>

<script>
    document.getElementById('searchForm').addEventListener('submit', function (event) {
        event.preventDefault();
        var account = document.getElementById('accountInput').value;
        var url = this.getAttribute('data-url') + '?account=' + account;

        // Show loading
        document.getElementById('loading').style.display = 'block';

        // Fetch images asynchronously
        fetch(url)
            .then(response => response.json())
            .then(data => {
                // Hide loading
                document.getElementById('loading').style.display = 'none';

                // Display images
                var imageGallery = document.getElementById('imageGallery');
                imageGallery.innerHTML = '';
                data.image_list.forEach(function (base64Image) {
                    var imgElement = document.createElement('img');
                    imgElement.src = 'data:image/jpeg;base64,' + base64Image;
                    imgElement.alt = 'Instagram Image';
                    imageGallery.appendChild(imgElement);
                });
            })
            .catch(error => {
                console.error('Error fetching images:', error);
                // Handle error (e.g., display an error message)
            });
    });
</script>

    {% block content %}
    {% endblock %}
</body>

</html>

instaImg_crawl/main/templates/main/find_id.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;600;700&display=swap" rel="stylesheet">

    <!-- Jquery -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background: #FAFAFA;
        }

        .phone-container {
            position: relative;
            width: 400px;
            height: 600px;
            margin-right: -10%;
        }

        .phone-image {
            position: absolute;
            top: -130px;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: contain;
        }

        .card {
            background-color: rgba(255, 255, 255, 0.8);
            width: 388px;
            height: 552px;
            position: relative;
            padding: 20px;
            margin: 0 auto;
            border-radius: 10px;
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            align-items: center;
        }

        .card img {
            width: 96px;
            height: 96px;
            margin-top: 20px;
        }

        .problem-text {
            font-size: 16px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            font-weight: bold;
            width: 300px;
            text-align: center;
            margin-top: 20px;
        }

        .help-text {
            font-size: 14px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            width: 300px;
            text-align: center;
            margin-top: 20px;
        }

        .input-box {
            width: 290px;
            height: 38px;
            margin-top: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
            padding: 0 10px;
        }

        .submit-btn {
            width: 300px;
            height: 30px;
            background-color: #b2dffc;
            color: white;
            border: none;
            border-radius: 5px;
            margin-top: 20px;
            font-size: 16px;
            cursor: not-allowed;
        }

        .submit-btn.enabled {
            background-color: #3897f0;
            cursor: pointer;
        }

        .reset-password {
            font-size: 12px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            width: 300px;
            color: #00376B;
            text-align: center;
            margin-top: 20px;
        }

        .or-text {
            display: flex;
            align-items: center;
            color: #737373;
            font-size: 13px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            width: 300px;
            margin-top: 20px;
        }

        .or-text::before,
        .or-text::after {
            content: "";
            flex: 1;
            border-bottom: 1px solid #737373;
        }

        .or-text::before {
            margin-right: .25em;
        }

        .or-text::after {
            margin-left: .25em;
        }

        .create-account {
            font-size: 14px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            width: 300px;
            color: #262626;
            text-align: center;
            margin-top: 20px;
        }

        .back-to-login {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: #FAFAFA;
            width: 388px;
            height: 44px;
            font-size: 14px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #262626;
            margin-top: 20px;
        }
    </style>

    <script>
    $(document).ready(function() {
        $('.input-box').on('input', function() {
            var first_name = $('#first_name').val();
            var last_name = $('#last_name').val();
            var email = $('#email').val();

            if (first_name && last_name && email) {
                $('.submit-btn').addClass('enabled');
                $('.submit-btn').prop('disabled', false);
            } else {
                $('.submit-btn').removeClass('enabled');
                $('.submit-btn').prop('disabled', true);
            }
        });

        $('.submit-btn').on('click', function() {
            var first_name = $('#first_name').val();
            var last_name = $('#last_name').val();
            var email = $('#email').val();

            $.ajax({
                url: '{% url "main:find_user" %}',
                method: 'POST',
                data: {
                    'first_name': first_name,
                    'last_name': last_name,
                    'email': email,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response) {
                    if (response.found) {
                        alert('사용자를 찾았습니다. 아이디: ' + response.username);
                    } else {
                        alert('일치하는 사용자를 찾을 수 없습니다.');
                    }
                },
                error: function() {
                    alert('서버 에러가 발생했습니다.');
                }
            });
        });
    });
</script>


    <title>아이디 찾기</title>
</head>

<body style="background: #FAFAFA">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
        <div class="container px-5">
            <a class="navbar-brand fw-bold" href="{% url 'main:main' %}">
                <span class="material-symbols-outlined" style="vertical-align: -4px;">photo_camera</span>
                Instagram
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"> Menu <i
                    class="bi-list"></i> </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                    <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'main:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'main:signup' %}">Sign Up</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="card">
        <img src="/static/photo/lock.png" alt="Lock Icon">
        <div class="problem-text">로그인에 문제가 있나요?</div>
        <div class="help-text">사용자 이름과 이메일 주소를 입력하시면 계정에 다시 찾도록 도와드릴게요.</div>
        <input type="text" id="first_name" class="input-box" placeholder="성">
        <input type="text" id="last_name" class="input-box" placeholder="이름">
        <input type="text" id="email" class="input-box" placeholder="이메일 주소">
        <button type="submit" class="submit-btn" disabled>확인</button>
        <a href="{% url 'main:password_reset' %}" class="reset-password">비밀번호를 재설정할 수 없나요?</a>
        <div class="or-text">또는</div>
        <a href="{% url 'main:signup' %}" class="create-account">새 계정 만들기</a>
        <a href="{% url 'main:login' %}" class="back-to-login">로그인으로 돌아가기</a>
    </div>
</body>
</html>

instaImg_crawl/main/templates/main/index.html
<!-- main/templates/main/index.html -->

{% extends 'main/base.html' %}

{% block content %}
    <h1>인스타그램 사진가져오기</h1>

    <div id="loading">Loading...</div>
    <div id="imageGallery"></div>

    <script>
        document.getElementById('searchForm').addEventListener('submit', function (event) {
            event.preventDefault();
            var account = document.getElementById('accountInput').value;
            var url = this.getAttribute('data-url') + '?account=' + account;

            fetchImages(url);
        });

        function showFolders() {
            var url = "{% url 'main:folder_list' %}";

            fetch(url)
                .then(response => response.json())
                .then(data => {
                    var imageGallery = document.getElementById('imageGallery');
                    imageGallery.innerHTML = '';
                    data.folder_names.forEach(function (folder_name) {
                        var folderElement = document.createElement('div');
                        folderElement.textContent = folder_name;
                        folderElement.addEventListener('click', function() {
                            showFolderImages(folder_name);
                        });
                        imageGallery.appendChild(folderElement);
                    });
                })
                .catch(error => {
                    console.error('Error fetching folders:', error);
                });
        }

        function showFolderImages(folder_name) {
            var url = "{% url 'main:show_folder_images' folder_name='dummy' %}".replace('dummy', folder_name);

            fetchImages(url);
        }

        function fetchImages(url) {
            document.getElementById('loading').style.display = 'block';

            fetch(url)
                .then(response => response.json())
                .then(data => {
                    document.getElementById('loading').style.display = 'none';

                    var imageGallery = document.getElementById('imageGallery');
                    imageGallery.innerHTML = '';
                    data.image_list.forEach(function (base64Image) {
                        var imgElement = document.createElement('img');
                        imgElement.src = 'data:image/jpeg;base64,' + base64Image;
                        imgElement.alt = data.folder_name + ' Image';
                        imageGallery.appendChild(imgElement);
                    });
                })
                .catch(error => {
                    console.error('Error fetching images:', error);
                });
        }
    </script>
{% endblock %}

instaImg_crawl/main/templates/main/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>